language: node_js

matrix:
  include:
    - node_js: 8
      env: RELEASE="true"
    - node_js: 9
    - node_js: 10

deploy:
  provider: npm
  email: npmjs@paysera.com
  api_key:
    secure: jdlI/T6o1Lo8B9Y1iGcZAaY1fimBhbVLm8bZ6JfFVhXpDwwkISpLRemrMf89Sqb/Z2hPuyikfhZme5XV5AlqWAyTP7T5bWaWHmh9vESDL10FiGnAYR4xo7XbI5rfwBE/djzdF0cV7fnaFGYnZSYoVt1HwuNpT8FhBW525KBKGKoSXLsw33UuJqeBHJ3EHuqBYu2FgH7trDYHSpijql9DYaSl8v1itzHYL9YPPLOTvBkOBU1pcVfd4cjBdbDoI9arazE71xP9A5QqO5Fx5y7HsBiIirKEWqYkMkoe1A2x0i5LCnDGByeJ8hcBktLOOKZc5QaJNhnVLDQEPyzv+hQdZ7owETehGmcnO02r4T3o8Uvu12WdydE071V/lvw1S8PJhyhIkL8y/yCp6QB29s8cy1OidjQqu6GVxHfxJqCov4WjPzEtFS1D/8jZMUcasGzs2Lv9WE9VwWN46LAfPDwejxfpKUfYlhBf9Pv90VNuLKLnisoy4G9xeRI+tYisQjDHoNKxdOZpH//6gjHJYXNyn49XpSJaveQ4/7US3d7/Mt/ymBEUtwLMH6Nm1W+w7jVLY/MFc6HUhK/QUgtD0I798A5W8BnfpsZhIS0v+r8wJZTRYZKGrWK8nFRTH/EZBYfYK5ngKLVJ3/M8D0ttcXhdA53X3Sc29U00dLcYkgOPeh8=
  on:
    tags: true
    repo: paysera/js-lib-redux-state-history
    condition: "$RELEASE = true"
  skip_cleanup: true

script:
  - npm run test:coverage && cat ./coverage/lcov.info | node_modules/.bin/coveralls
